<?php

 $title = 'Hapus Customer';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Apakah anda yakin ingin menghapus customer 
     '<?php echo $this->escapeHtml($this->request['nama']); ?>'
 </p>
 <?php
 $url = $this->url('pegawai', array(
     'action' => 'delete',
     'id'     => $this->request['id'],
 ));
 ?>
 <form action="" method="post">
 <div>
     <input class="btn btn-default" type="submit" name="Yes" value="Yes" />
     <a href="<?php echo $this->url('customer', array('action' => 'index')) ?>" class="btn btn-default" > No </a>
 </div>
 </form>